/** Version 2.2 */
CREATE TABLE WEL_ACCESSKEY ( 
  IDACCESSKEY  	NUMBER, 
  TAB      		NUMBER, 
  ACCESSKEY     VARCHAR2 (255), 
  LABEL    		VARCHAR2 (255), 
  TYPE     		VARCHAR2 (25),
  VERSION		VARCHAR2 (6),
  DATE			DATETIME) ; 

CREATE TABLE WEL_PROFILE ( 
  IDPROFILE     VARCHAR2 (30), 
  NAME          VARCHAR2 (255),
  VERSION		VARCHAR2 (6),
  DATE			DATETIME ) ; 

CREATE TABLE WEL_PROFILE_ACCESSKEY_INTERNAL ( 
  IDPROFILE  	VARCHAR2 (30), 
  IDACCESSKEY   NUMBER, 
  ACCESSKEY     VARCHAR2 (255), 
  VALUE     	VARCHAR2 (255),
  VERSION		VARCHAR2 (6),
  DATE			DATETIME  ) ; 

CREATE TABLE WEL_PROFILSDROITS ( 
  IDPROFILE  		VARCHAR2 (30), 
  ACCESSKEY      	VARCHAR2 (255), 
  VALUE     		VARCHAR2 (255),
  VERSION			VARCHAR2 (6),
  DATE				DATETIME  ) ; 
  
  
CREATE TABLE WEL_ADDONS ( 
  NAME  	    VARCHAR2 (30), 
  DISPLAYNAME   VARCHAR2 (255), 
  VERSION		VARCHAR2 (6),
  DATE			DATETIME) ; 
  
  