-- #####################################################
-- Modification for the manual practice comments

--Add the comments table
create table QualityResult_Comment (
    QR_CommentId bigint generated by default as identity (start with 1),
    Comments varchar(4000),
    QualityResultId bigint,
    primary key (QR_CommentId),
    unique (QualityResultId)
);

alter table QualityResult_Comment 
    add constraint FKD36C3ADCCCF6BB41 
    foreign key (QualityResultId) 
    references QualityResult;