alter table AUDITBO modify SQUALE_VERSION default '7.1' ;
alter table COMPONENT modify STARTLINE default 0 ;
alter table COMPONENT modify EXTERNAL_DEV default 1 ;
alter table COMPONENT modify IN_PRODUCTION default 1 ;
alter table COMPONENT modify InInitialDev default 1;
alter table COMPONENT modify QualityApproachOnStart default 1;
alter table COMPONENT modify GlobalCost default 0;
alter table COMPONENT modify DevCost default 0;
alter table CRITERIUMPRACTICE_RULE modify WEIGHT default 1 ;
alter table FACTORCRITERIUM_RULE modify WEIGHT default 1 ;
alter table QUALITYRULE modify WEIGHTFUNCTION default null ;
alter table RULECHECKINGTRANSGRESSIONITEM modify LINE default 0 ;
alter table TASK modify STANDARD default 0 ;
alter table TASK modify MANDATORY default 0 ;
alter table TASKS_USER modify EXPORT_IDE default 1 ;
alter table USERBO modify UNSUBSCRIBED default 0 ;
alter table ApplicationLastExport modify ToExport default 0 ;
commit;