-- #####################################################
-- Modification for the manual practice comments

--Add the comments table
create table QualityResult_Comment (
    QR_CommentId bigint generated by default as identity (start with 1),
    Comments varchar(4000),
    QualityResultId bigint,
    primary key (QR_CommentId),
    unique (QualityResultId)
);

alter table QualityResult_Comment 
    add constraint FKD36C3ADCCCF6BB41 
    foreign key (QualityResultId) 
    references QualityResult;
    
-- Modification for #208 
alter table Component add QualityApproachOnStart bit;
alter table Component add InInitialDev bit;
alter table Component add GlobalCost integer;
alter table Component add DevCost integer;
alter table Component alter InInitialDev set default 1;
alter table Component alter QualityApproachOnStart set default 0;
alter table Component alter GlobalCost set default 0;
alter table Component alter DevCost set default 0;
update Component set InInitialDev=1, QualityApproachOnStart=0 , GlobalCost=0 , DevCost=0;
